### ISSUE TITLE
Feature Request: Structure support

### ISSUE THREAD

**Issue by Duatao7055** [viniciusgf2/Ambience#10]
Is your feature request related to a problem? Please describe.
Structures are pretty cool, and support for more structures would be awesome, even though you said that you could only detect them using structure specific mobs. Pretty much the only other structures you might be able to add support to is the end portal inside the stronghold, because of the silverfish spawner, and mineshafts, because of the cave spider spawner. So, I came up with a maybe better solution.

Describe the solution you'd like
Create a new event or category or whatever to add specific blocks. An example is block.minecraft:stone=Stone. This would play the song Stone when near vanilla minecraft stone blocks. This could be used with other mods to create structures with special blocks that only exist in that created structure, allowing structure support without adding structure support. I'm not sure of what the distance from the player detecting these blocks would be, but probably similar to detection for villagers for the village event.

Describe alternatives you've considered
Use the area event.

Additional context
No.

**Comment by viniciusgf2** [comment]
This one I'm not sure if it is possible, the way the music for the villages plays are by counting how many villagers are near the player if there are more than 5 than it triggers the village music, I've added an event for the ocean monument for the next version, but for the desert temple as there aren't any special entity or mob there I don't know

**Comment by viniciusgf2** [comment]
I've implemented the structure support in the last version for the vanilla structures :D
