### ISSUE TITLE
Feature Request: Song Display

### ISSUE THREAD

**Issue by Duatao7055** [viniciusgf2/Ambience#14]
A constant song display option without needing the F3 screen open would be awesome, as well as the option to move its place on the screen.

**Comment by viniciusgf2** [comment]
I can add that but I don't know if it's a good idea, there are a lot of places like inside houses with lots sub regions inside, that it change the music quite a lot, it will spam the musics in the screen.

**Comment by viniciusgf2** [comment]
It's easy to implement but the information in F3 are good enough, so I will close this
