### ISSUE TITLE
Feature Request: Keybind events

### ISSUE THREAD

**Issue by Duatao7055** [viniciusgf2/Ambience#15]
An event for playing music when pressing a keybind, spelled out in the controls menu.

**Comment by viniciusgf2** [comment]
This one I have done already for next version, you can configure musics to play pra pressing 10 keys on the client and if you are an op in a server you can make the music play for everyone by pressing Shift+[key]

**Comment by viniciusgf2** [comment]
I have implemented this for the 1.12 and 1.15 on the last versions, thanks for the suggestion.
