### ISSUE TITLE
Feature Request: Block that controls music

### ISSUE THREAD

**Issue by Duatao7055** [viniciusgf2/Ambience#17]
Generic title, I know. I was thinking of a block that you could place down that you could save a specified area, by using the soundnizer on it. This is something that might make the mod compatible with custom structures. I have no idea if Recurrent complex or other structure generators would save the info from a block like this, but it would be cool nonetheless. Or perhaps the block can fill in an entire area and breaks upon generation, creating no particles but acting as if a soundnizer had specified that area to play music. I don't know. I have a crap ton of ideas and implementations, but I have no idea of the difficulty or ability to implement them.

**Comment by viniciusgf2** [comment]
I tried once to do that for the Recurrent complex structure but they don't have any kind of variable saved saying that the generated structure are in that region, I could only see the list of possible structures to add a new one or get some structure but I don't have the coordinates to know when to play the music, but it would be cool if they had added these kind of information somehow

**Comment by Duatao7055** [comment]
Ima close this now since it seems like this will probably not happen unless another mod adds support.
