### ISSUE TITLE
Feature Request: Control over fading and time between songs

### ISSUE THREAD

**Issue by Duatao7055** [viniciusgf2/Ambience#18]
**Is your feature request related to a problem? Please describe.
Having control over the fading and time between songs would be pretty awesome, since as it is right now, the next song starts, and then fades out and fades in.

Describe the solution you'd like
First of all, fading should happen before the next song starts by default, that is probably a bug. Then, you would be able to specify the number of ticks it takes for a song to fade out, the number of ticks of silence between songs, and the number of ticks for the next song to fade in.

Describe alternatives you've considered
Deal with the current fading timing, or do some resource pack magic to play music with less flexibility than this mod.

Additional context
Nope.

**Comment by viniciusgf2** [comment]
I will consider it for the next update

**Comment by viniciusgf2** [comment]
It's implemented in the last release, enjoy :smiley:
