### ISSUE TITLE
[BUG] Water Particle Sound Crash?

### ISSUE THREAD

**Issue by Eckszy** [viniciusgf2/Ambience#20]
The bug appears to be that the water particle droplet and/or the sound produced by them that was recently added is crashing the game client-side. 

This crash occured in Multiplayer, but only client side.

[crash-2020-09-07_19.10.47-client.txt](https://github.com/viniciusgf2/Ambience/files/5185727/crash-2020-09-07_19.10.47-client.txt)
[crash-2020-09-07_19.11.53-client.txt](https://github.com/viniciusgf2/Ambience/files/5185728/crash-2020-09-07_19.11.53-client.txt)
[crash-2020-09-07_19.13.24-client.txt](https://github.com/viniciusgf2/Ambience/files/5185729/crash-2020-09-07_19.13.24-client.txt)

The mods I use are listed in the crash report.
I have more crash reports that I believe are of the same bug if needed.

This is on Ambience Extras 1.5.0 for 1.12.2.
I've experienced this crash about 6 times, I would recommend possibly allowing the droplet addition to be toggled in the config.

For further context, I had another player playing with me on the server but they were not crashing. The main difference however, is that they have particles disabled/minimal, which causes the water particle droplets to not be visible AND produce no sound via ambience extras.

**Comment by Eckszy** [comment]
It seems that setting my own particles to 'decreased' does not prevent the crash, however, the particles (and sound) do not appear on the 'minimal' setting, which is actually a step up from decreased. I do not crash on 'minimal'.

**Comment by CmdrJane** [comment]
Happend to me in singleplayer world, crash report: https://pastebin.com/apkqyiZf

**Comment by viniciusgf2** [comment]
I will check this after I finish the last version this weekend

**Comment by Eckszy** [comment]
It could potentially be linked to the lack of an event.dripwaterincave in our ambience.properties file, though I'm not sure why it's not falling back on generic in that case. I'll test it later today.

**Comment by viniciusgf2** [comment]
This was caused by the way the mod were treating the dripping water sound fx, I've changed the class and it should work now, please check if it's working in the last versions

**Comment by Eckszy** [comment]
It seems to be functioning properly now, playing on the "All" particles setting and seeing/hearing the dripping water fx does not appear to cause any crashes from my testing. Thanks!
