### ISSUE TITLE
Creating music areas through commands

### ISSUE THREAD

**Issue by CmdrJane** [viniciusgf2/Ambience#21]
When soudinizer tool is a cool thing it will be really awesome to have a command that will allow to do same thing. Why? For command blocks ofc. It will allow for automated creation of music areas which will be powerful tool combined with RComplex.
So basically the command itself should be something like /fill command with 2 sets of coordinates and support for relative coords.

**Comment by viniciusgf2** [comment]
oh I didn't know that is possible to run commands on recurrent complex to make this kind of things, btw this is something that is in my list to make, there are some areas that is hard to make using only the soundnizer tool without you have to break a block inside your house por example to select the corner of the room

**Comment by viniciusgf2** [comment]
I've implemented the commands for Creating/Edit/Remove regions through commands now :smiley: see the wiki [here](https://github.com/viniciusgf2/Ambience/wiki/Area-Commands) for help
