### ISSUE TITLE
[BUG] Ambience mod crashes game (Issue with Water Dripping Particles)

### ISSUE THREAD

**Issue by knoxhack** [viniciusgf2/Ambience#23]
**Describe the bug**
Ambience mod crashes game

**Where playing in SinglePlayer or Multiplayer?**
-SinglePlayer

**Mods used or modpack (please complete the following information):**
 - Modpack: Astroblock 2 - [https://www.curseforge.com/minecraft/modpacks/astroblock-2](https://www.curseforge.com/minecraft/modpacks/astroblock-2)

**Mod Version used:
- Ambience-1.12.2-1.5.0

**Please send the followings files to help track the issue:
- [https://github.com/NFINIT-Development/Astroblock2/files/5219291/crash-2020-09-14_17.01.53-client.txt](https://github.com/NFINIT-Development/Astroblock2/files/5219291/crash-2020-09-14_17.01.53-client.txt)

**Comment by viniciusgf2** [comment]
This was caused by the way the mod were treating the dripping water sound fx, should work now, please check if it's working now

**Comment by wolfkidsounds** [comment]
I've tested the latest version on my server today and had a similar (or the same?) crash as described here.

**Describe the bug**
When joining the multiplayer server, the game crashes after loading several chunks.

**Where playing in SinglePlayer or Multiplayer?**
Multiplayer

**Mods used or modpack (please complete the following information)**
- Custom Selfmade Modpack

**Mod Version used**
Ambience-1.12.2-1.6.0

**Please send the followings files to help track the issue**
[crash.txt](https://github.com/viniciusgf2/Ambience/files/5258749/crash.txt)

---

*Sidenote: Thanks for keeping this up, I really love experimenting with it, and i really want to keep it inside the pack. It really is adding a lot!*

**Comment by wolfkidsounds** [comment]
I've also tested this in singleplayer with only optifine, dynamic sorroundings (and dependencies) installed, where it works properly and does not crash.

**Comment by viniciusgf2** [comment]
strange, you can disable it in the server config file by setting the "Water Dripping"=false for now, I will do more tests could be some incompatibility with other mod that override the particles too

**Comment by wolfkidsounds** [comment]
Thank you, I would See *Dynamic Surroundings* and *weather2* as potential conflicts I guess? 
If there is something I can help with, let me know :)

**Comment by wolfkidsounds** [comment]
This workaround works in two ways. 
A: Disabling Lava/Water Dripping inside the Minecraft Options (Animations)
B: Disabling the feature in the mod configuraiton.

Both work.

**Comment by viniciusgf2** [comment]
issue seens to be resolved
