### ISSUE TITLE
Support for Gamestages

### ISSUE THREAD

**Issue by Duatao7055** [viniciusgf2/Ambience#24]
**Is your feature request related to a problem? Please describe.**
I'm slowly developing a modpack, and I would like the music to be able to change based on the stage that you are in.

**Describe the solution you'd like**
Going back to my idea of modular events, a stage could be defined as a modifier for an event dependency to play. An example of this would be a line like stage.(stagename)=Stage1

**Describe alternatives you've considered**
I just use the current events I have with this mod. This feature is not necessary, but is nice.

**Additional context**
I don't think this should be very high priority, if you even consider it, since there are already plenty enough options to choose from for events for music, but this is just a suggestion of something that would be nice to have for modpacks that really focus on the music.

**Comment by viniciusgf2** [comment]
I thought about that but it's too much, it will cause confusion to configure as it now people already have issues to configure the ambience.properties as it is
