### ISSUE TITLE
[BUG] Instant Play option no longer works.

### ISSUE THREAD

**Issue by Eckszy** [viniciusgf2/Ambience#26]
On 1.12.2 1.6.0, all regions that previously had Instant Play ticked no longer actually instant play.
Tested unticking instant play, saving region, and ticking it on again, still nothing.
Tested making a new region and ticking on instant play, still nothing.

Playing on a multiplayer server, so tested it with another player's sound, same issue.

**Comment by viniciusgf2** [comment]
Thanks for reporting, its fixed now in the last release
