### ISSUE TITLE
[BUG] Crash that has something to do with water

### ISSUE THREAD

**Issue by Spaghet4Life** [viniciusgf2/Ambience#27]
**Describe the bug**
I'm playing on the AstroBlock modpack and about 3 seconds after placing water my game crashed. I tried to rejoin but I was met with an instant crash

**Where playing in SinglePlayer or Multiplayer?**
-SinglePlayer

**To Reproduce**
1. Download AstroBlock modpack
2. Make water with an oak crucible
3. Place it in the world and crash

**Expected behavior**
The game shouldn't crash

**Screenshots**
Not necessary

**Mods used or modpack (please complete the following information):**
 - AstroBlock

**Mod Version used:
-1.5.0

**Please send the followings files to help track the issue:
-..\ambience_music\ambience.properties 
-..\logs\latest.log 
-..\crash-reports\crash-(last date)-server (none since I'm on singleplayer)
-..\crash-reports\crash-(last date)-client 
[Logs.zip](https://github.com/viniciusgf2/Ambience/files/5260117/Logs.zip)

**Additional context**
None

**Comment by viniciusgf2** [comment]
This issue was already reported and still under investigation, there are workarounds[ here ](https://github.com/viniciusgf2/Ambience/issues/23)
