### ISSUE TITLE
[Feature Request] - Per Song Fade in AND Fade Out? (Or even Crossfade?)

### ISSUE THREAD

**Issue by wolfkidsounds** [viniciusgf2/Ambience#28]
**Is your feature request related to a problem? Please describe.**
I sometimes work with ambience loops and/or songs that kind of don't have a specific start and end. When using the mod, sometimes the songs cut off very rapidly or (since the new version) fade out to silence and then come back again..

**Describe the solution you'd like**
I would like to define on a per song basis the time that it fades in, the time it fades out, or if it should crossfade to the next song.
Maybe also as a "tick" option when using the sound-nicer tool?

**Describe alternatives you've considered**
No mod so far that provides the flexibility and I've not found a way to have that feature, so I'd like to ask :)

**Additional context**
I think in essence, one of the two options (fade in and out time control per song, or crossfade control) would do the trick and make the mod much more flexible for me :)

**Comment by viniciusgf2** [comment]
I thought on making this too on the beginning but I was able to only make it fade out the volume to 0, change the music and fade in back to 1 again because the music player is able to play only one music at time

**Comment by wolfkidsounds** [comment]
Hmmn, do you maybe know a way I could achieve that type of effect?

**Comment by viniciusgf2** [comment]
there is no way, to make that, I have to rewrite the core of mod made by vazkii

**Comment by wolfkidsounds** [comment]
Okay, however, still thank you for mod! :) !
