### ISSUE TITLE
[Feature Request] - Feathered Area

### ISSUE THREAD

**Issue by wolfkidsounds** [viniciusgf2/Ambience#30]
**Is your feature request related to a problem? Please describe.**
When going from one region to another, the sound sometimes switches instantly.

**Describe the solution you'd like**
It would be cool if when we select an area, we could have an area around the selection where the sound gradually fades in. As we set a center point (which is the selected area) where the sound reaches its full volume potential, while we can select a certain area and the actual area where the sound is fading in (for example in the size of blocks). -> Therefore it would be necessary to play the two sounds at the same time (area.before - area.now+fadingarea)

**Describe alternatives you've considered**
Alternatively, we could go back to the idea of #28 (crossfading two sounds when a new area is triggered).

**Additional context**
It's just an idea, that would make it a little nicer when working with ambiance type sounds...

**Comment by viniciusgf2** [comment]
I was thinking how to make it, but the complexity involved to make it work not worth it to implement
