### ISSUE TITLE
More smooth fade in/out

### ISSUE THREAD

**Issue by SettingDust** [viniciusgf2/Ambience#31]
**Is your feature request related to a problem? Please describe.**
The bgm switchs suddenly

**Describe the solution you'd like**
Maybe the prev one fade out and next fade in together? Now, there is a blank time between two music

**Comment by viniciusgf2** [comment]
it isn't possible, the core of the mod was made in a way that only one music can be played at a time

**Comment by SettingDust** [comment]
> 
> 
> it isn't possible, the core of the mod was made in a way that only one music can be played at a time

Alright. Thanks
