### ISSUE TITLE
[Feature Request] Blood Moon Support

### ISSUE THREAD

**Issue by TCreopargh** [viniciusgf2/Ambience#32]
**Is your feature request related to a problem? Please describe.**
I want to add some epic battle music when a bloodmoon is active (or simply play terraria's bloodmoon music to make players know that there's a blood moon happening. Since I've disabled the red moon rendering of blood moon mod for compatibility with shaders, the only way for someone to check if a bloodmoon is active is going to bed, which can't be done at all times.
bloodmoon mod: https://www.curseforge.com/minecraft/mc-mods/bloodmoon

**Describe the solution you'd like**
Add events when a blood moon is active, like event.bloodmoon=bloodmoon

**Describe alternatives you've considered**
There is no alternative I can think of

**Additional context**
Only one event is ok, but adding sub-events like event.bloodmoonBattle or event.bloodmoonUnderground would be better!

**Comment by CalaMariGold** [comment]
I'd suggest using Nyx's bloodmoons as they're more configurable and is actually being updated.

https://www.curseforge.com/minecraft/mc-mods/nyx

**Comment by viniciusgf2** [comment]
I've took a look to add this mod event, but it's too outdated and it gives a lot of errors when trying to add as dependency so there is no way to add this feature :(

**Comment by CalaMariGold** [comment]
What do you mean outdated? Did you look at Nyx? I'm in contact with the dev and could ask for some support. What exactly do you need?
