### ISSUE TITLE
[BUG]Crash on Player Hurt Event

### ISSUE THREAD

**Issue by Cuboid404** [viniciusgf2/Ambience#33]
**Describe the bug**
Game Simply Crashes upon any damage event to the player. like stubbing your toe.

**Where playing in SinglePlayer or Multiplayer?**
Singleplayer & Multiplayer

**To Reproduce**
For example; 
1. 4 block high nerdpole
2. jump off
3. Stub your toe and...
4. Crash in a way completely unrelated to gravity.

**Expected behavior**
The event Player.Hurt to play or smth. a crash is a crash, i doubt its normal.

**Screenshots**
*Insert picture of 4 block high pillar*

**Mods used or modpack (please complete the following information):**
-Ambience EXTRAS (this mod)

**Mod Version used:
-1.12.2-1.7.0

**Please send the followings files to help track the issue:
-..\crash-reports\crash-(last date)-server (i do not have this)

[ambience.properties.txt](https://github.com/viniciusgf2/Ambience/files/5321866/ambience.properties.txt)
(i converted it to .txt to put it here)
[crash-2020-10-03_16.56.59-client.txt](https://github.com/viniciusgf2/Ambience/files/5321863/crash-2020-10-03_16.56.59-client.txt)
[latest.log](https://github.com/viniciusgf2/Ambience/files/5321864/latest.log)

**Additional context**
The Entire mod is completely silent. im using your music-pack and no other mods.

**Comment by viniciusgf2** [comment]
try to use the new version 1.12.2-1.7.2 all sort of errors where popping for those that didn't have the ambience resource pack enabled, now this is fixed

**Comment by viniciusgf2** [comment]
bug fixed in the last release
