### ISSUE TITLE
[BUG] Log weird

### ISSUE THREAD

**Issue by SettingDust** [viniciusgf2/Ambience#34]
**Describe the bug**
1. The background music of vanilla isn't disabled. (Maybe only in mainmenu)
2. Log after a while in mainmenu

**To Reproduce**
1. Start game
2. wait

**Mod Version used:
-Mod Version 1.12.2-1.7.0

**Please send the followings files to help track the issue:
-..\ambience_music\ambience.properties
https://paste.ubuntu.com/p/PvD3tKsCVF/
-..\logs\latest.log
https://paste.ubuntu.com/p/v3tgWdnh4m/

**Additional context**
[Thread-11/ERROR] [net.minecraft.client.audio.SoundManager]: Error in class 'SourceLWJGL OpenAL'
[Thread-11/ERROR] [net.minecraft.client.audio.SoundManager]: Channel null in method 'stop'
[Thread-11/ERROR] [net.minecraft.client.audio.SoundManager]: Error in class 'SourceLWJGL OpenAL'
[Thread-11/ERROR] [net.minecraft.client.audio.SoundManager]: Channel null in method 'stop'
[Thread-11/ERROR] [net.minecraft.client.audio.SoundManager]: Error in class 'SourceLWJGL OpenAL'
[Thread-11/ERROR] [net.minecraft.client.audio.SoundManager]: Channel null in method 'stop'
[Ambience Player Thread/INFO] [STDERR]: [vazkii.ambience.PlayerThread:run:74]: java.lang.NullPointerException
[Ambience Player Thread/INFO] [STDERR]: [vazkii.ambience.PlayerThread:run:74]: 	at vazkii.ambience.SongLoader.getStream(SongLoader.java:206)
[Ambience Player Thread/INFO] [STDERR]: [vazkii.ambience.PlayerThread:run:74]: 	at vazkii.ambience.PlayerThread.run(PlayerThread.java:54)
[Thread-11/ERROR] [net.minecraft.client.audio.SoundManager]: Error in class 'SourceLWJGL OpenAL'
[Thread-11/ERROR] [net.minecraft.client.audio.SoundManager]: Channel null in method 'stop'
[Thread-11/ERROR] [net.minecraft.client.audio.SoundManager]: Error in class 'SourceLWJGL OpenAL'
[Thread-11/ERROR] [net.minecraft.client.audio.SoundManager]: Channel null in method 'stop'

**Comment by viniciusgf2** [comment]
try to use the new version 1.12.2-1.7.2 all sort of errors where popping for those that didn't have the ambience resource pack enabled, now this is fixed

**Comment by viniciusgf2** [comment]
closing it as this was solved some versions ago
