### ISSUE TITLE
[BUG] Breaking an Ocarina crashes the game

### ISSUE THREAD

**Issue by NyanMC** [viniciusgf2/Ambience#39]
**Describe the bug**
After using the last piece of durability on an Ocarina it will instantly break instead of saying "You played (song name)". Trying to play (or hold) another Ocarina will crash the game.

Edit: you don't even need to play a second ocarina, just play the first one and break it

**Where playing in SinglePlayer or Multiplayer?**
-SinglePlayer

**To Reproduce**
When the Ocarina has only a single use left (0 durability, durability bar empty), play any song. The Ocarina will break on playing the last note. Next, hold another Ocarina.

**Expected behavior**
Ocarina doesn't instantly break and goes through the cutscene as normal, game doesn't crash when using another one

**Screenshots**
Not applicable

**Mods used or modpack (please complete the following information):**
mod list will appear in the crash log

**Mod Version used:
1.7.5

**Please send the followings files to help track the issue:
ambience config: https://hastebin.com/koniwimobi.apache
(this is awkward, my latest.log is too large to be opened by any text editor, if needed i can reproduce the crash again and send a latest.log for that)
(wasn't provided a crash server file)
crash client: https://hastebin.com/tacewamica.yaml

**Comment by viniciusgf2** [comment]
this was fixed in the last update, thanks for reporting :)
