### ISSUE TITLE
[Solved, user issue] Music not playing when supposed to/at all. Basically, music plays one song then stops forever.

### ISSUE THREAD

**Issue by roccscout** [viniciusgf2/Ambience#42]
**Version 1.12.2**

**Describe the bug**
I have a large config folder with lots of music. When I launch the game, it plays the menu songs. when I join the game, it will switch the playing music over to the appropriate song type in survival/creative, BUT, it will play that one first song, then stop. Soon as a song finishes, it will not play another one.

**Where playing in SinglePlayer or Multiplayer?**
-SinglePlayer
-Multiplayer

**Expected behavior**
I expect that, for the songs for "night" event, they will play when it's night time--not the case.
Boss songs? They'll play once initially, then will not play again.
Dimension songs? Play once, then not again.

**Please send the followings files to help track the issue:
-..\ambience_music\ambience.properties

**see my properties HERE: https://pastebin.com/5tTpzQEd**

**Additional context**

**Comment by roccscout** [comment]
Looks like it was fixed in the most recent update.

**Comment by viniciusgf2** [comment]
hm... strange, I didn't change nothing in the code related to that in the last update, the changes where all related to some bugs in the ocarina

**Comment by roccscout** [comment]
I take that back-- it's not fixed.

Is it because of a timer of some kind? I cannot get music to play during the day... or at night...

Like I said: it plays for a song or two, but then stops. Forever.

Music will stop playing, but when I approach a boss it won't start playing. Once it stops, it stops.

**Comment by viniciusgf2** [comment]
Oh your ambience.properties is wrong, you can't do this:

event.village=
event.underwater=
event.boat=
event.horse=
event.pig=

To remove an event you have to or delete it completely or comment it with "#" :

#event.villageNight=hatenovillagenight,gerudotownnight
#event.credits=maintheme
#event.horde=battlestrong
#event.nether=WintersBreath
#event.end=ruins
#event.bossWither=calamity
#event.bossDragon=darkbeast

**Comment by roccscout** [comment]
Thank you for the comment! I ended up discovering the same thing last night. I'd like to leave this "issue" up (marked as solved?) for other noobs to see!

**Comment by viniciusgf2** [comment]
closing as it is solved
