### ISSUE TITLE
[BUG] Nullpointerexception related to your mod causes game to crash

### ISSUE THREAD

**Issue by WutHavUDun** [viniciusgf2/Ambience#5]
Game crashes after a while of playing (see crash report). There is a nullpointerexception which references the DripWaterParticleFactory. This typically seems to occur after loading a certain chunk (maybe something to do with world generation?). After the world crashes the first time, it will crash as soon as it is loaded if Ambience is not disabled beforehand.

I was in single player as I was testing to see if the mod was stable before we moved it to the server. I really like what this mod adds to the game so I'm hoping I can get this resolved so everyone can enjoy it.

Other Active Mods:

Additional Lights
Applied Energistics 2
Bibliocraft
Biomes 'O' Plenty
Biomes 'O' Plenty Patch
Chisel
Code ChickenLib
CoFH Core
CoFH World
Connected Textures Mod
Fast Async World Edit
Fast Leaf Decay
Gameshark
Gravestone
HWYLA
Inventory Tweaks
Just Enough Items
Journeymap
NVL Forcefields
Pam's Harvestcraft
Pixel Extras
Pixelmon
Redstone Flux
Rex's Additional Structures
Thermal Cultivation
Thermal Dynamics
Thermal Expansion
Thermal Foundation
Thermal Innovation
Waystones
Worldedit

All versions are for minecraft 1.12.2

[ambience_music.zip](https://github.com/viniciusgf2/Ambience/files/5169664/ambience_music.zip)
[crash-2020-09-03_10.19.02-client.txt](https://github.com/viniciusgf2/Ambience/files/5169665/crash-2020-09-03_10.19.02-client.txt)

**Comment by viniciusgf2** [comment]
What version of Ambience are you running? I've fixed this on the Ambience-1.12.2-1.5.0

**Comment by viniciusgf2** [comment]
This was fixed in the last update :)
