### ISSUE TITLE
Feature Request: Silence when a jukebox is playing

### ISSUE THREAD

**Issue by Duatao7055** [viniciusgf2/Ambience#6]
Music continues to play even when a music disc is placed in a jukebox, which leads to both the music disc and Ambience music playing at the same time. This should not occur, but is a feature request because the mod is probably working as intended, which is not compatible with a jukebox from minecraft.

**Comment by viniciusgf2** [comment]
Yes, I've noticied this yesterday when I've found a disc from minecraft in my world and put it to play in the jukebox, I will see if there is a way to detect when the jukebox is playing and stop the ambience.
