### ISSUE TITLE
How to fix the entity hit crashing

### ISSUE THREAD

**Issue by sirben99** [viniciusgf2/Ambience#69]
Hey!

Wanted to inform you that the mod crashes when hitting an entity, e.g. a creeper. This is because you uploaded wrong ambience.properties.

You have to download this music pack to get working: https://www.curseforge.com/minecraft/mc-mods/ambience-extras (Scroll down untill you see My personal Music pack)
This contains the file that you have to override to get it to work

If you dont, the game will crash when hitting something, since i think its trying to play something thats non-existant, and will crash.

The original comment was outcalled for and i edited this to make it more clear what the problem is and how to fix it. Im sorry.

**Comment by ShockedCoder** [comment]
Take your shitty attitude and weak ability to fix your own problems away from here. This mod was created for fun and in the dev's free time, if the mod is broken for you and you're not arsed to figure out why and fix it yourself, then kindly fuck off and never use this mod again.
![image](https://user-images.githubusercontent.com/40272709/111065871-add7f580-84c4-11eb-918e-b29ff0fec0fc.png)

**Comment by sirben99** [comment]
> Take your shitty attitude and weak ability to fix your own problems away from here. This mod was created for fun and in the dev's free time, if the mod is broken for you and you're not arsed to figure out why and fix it yourself, then kindly fuck off and never use this mod again.
> ![image](https://user-images.githubusercontent.com/40272709/111065871-add7f580-84c4-11eb-918e-b29ff0fec0fc.png)

Thank you for your kind message, but still, like i have said time and time again, its not only broken for ME and "the dev made it in his free time" is still not a valid argument. Look at the issues. And im not sure did you even read it, but i did fix it. Its, the whole point of the comment. Where do people get that i dont know how to fix problems? Its not my responcibility to fix them in a first place, but i did. And even made an lovely guide on how on HOW TO NOT CRASH UR GAME WHEN HITTING A MOB. Im not even going to bother with you lovely people defending lazy devs. Oh and maybe dont have an shitty attitude ur self when trying to call others out for theyr shitty attitudes eh? Kinda ironic dont you think? Have a good day :)!
